# -*- coding: utf-8 -*-
"""
Created on Tue Oct 16 19:57:56 2018

@author: alanyliu
"""

import re
import pydot
import filereadtest
import file_reader
import datetime

test = """
1.	A pulsed image capturing system, comprising:
a pulse generation circuit configured to generate a pulsed light pattern at an external object;
a dynamic vision sensor (DVS) including a pixel array having a plurality of pixels arranged in matrix form, wherein the plurality of pixels are configured to sense an amount of light from the pulsed light pattern reflected by the external object and output event signals; and
a DVS scanning and readout circuit configured to perform a DVS scanning and readout operation on the event signals received from the plurality of pixels to generate a DVS output,
wherein a global reset signal is transmitted to the plurality of pixels to set a reference illumination level for each of the plurality of pixels,
the pulsed light pattern is generated after the global reset signal is transmitted to the plurality of pixels,
a global hold signal is transmitted to the plurality of pixels, after the pulsed light pattern is generated, to hold an illumination change event indicating a change with respect to the reference illumination level for each of the plurality of pixels, 
the DVS scanning and readout operation is performed after the global hold signal is transmitted to the plurality of pixels, and
a captured reflection of the pulsed light pattern is extracted from the DVS output after cleaning DVS-related artifacts from the DVS output without additional image processing.

2.	The pulsed image capturing system of claim 1, wherein a process of transmitting the global reset signal, generating the pulsed light pattern, transmitting the global hold signal, and performing the DVS scanning and readout operation is repeated for a predetermined number of passes, and
the DVS output of the predetermined number of passes is averaged to generate a final DVS output.

3.	The pulsed image capturing system of claim 1, wherein the pulsed light pattern is generated by one of a light emitting diode (LED) or a vertical-cavity surface-emitting laser (VCSEL).

4.	The pulsed image capturing system of claim 1, wherein the pulsed light pattern includes a sequence of patterns.

5.	The pulsed image capturing system of claim 4, wherein the sequence of patterns includes at least two different patterns.

6.	The pulsed image capturing system of claim 1, wherein the global reset signal and the global hold signal are generated by one of the pulse generation circuit and the DVS scanning and readout circuit.

7.	The pulsed image capturing system of claim 1, wherein the global reset signal and the global hold signal are generated by an external controller.


8.	The pulsed image capturing system of claim 1, further comprising a configuration register configured to store a rate of capture of the pulsed image capturing system and to generate the global hold signal and the global reset signal.


9.	A pulsed image capturing system, comprising:
a pulse generation circuit configured to generate a pulsed light pattern at an external object;
a dynamic vision sensor (DVS) including a pixel array having a plurality of pixels arranged in matrix form, wherein the plurality of pixels are configured to perform a light sensing operation to sense an amount of light from the pulsed light pattern reflected by the external object and output event signals; 
a DVS scanning and readout circuit configured to perform a DVS scanning and readout operation on the event signals received from the plurality of pixels to generate a DVS output; and
a plurality of multiplexers configured to select a plurality of control signals,
wherein the plurality of control signals synchronize operation of the pulsed image capturing system such that the light sensing operation is performed after the pulsed light pattern is generated and before the DVS scanning and readout operation is performed.

10.	The pulsed image capturing system of claim 9, wherein the pulsed light pattern is generated, the light sensing operation is performed, and the DVS scanning and readout operation is performed for a predetermined number of passes, and
the DVS output of the predetermined number of passes is averaged to generate a final DVS output.

11.	The pulsed image capturing system of claim 9, wherein the pulsed light pattern is generated by one of a light emitting diode (LED) or a vertical-cavity surface-emitting laser (VCSEL).

12.	The pulsed image capturing system of claim 9, wherein the pulsed light pattern includes a sequence of patterns.


13.	The pulsed image capturing system of claim 9, further comprising a configuration register configured to store a rate of capture of the pulsed image capturing system and to generate the plurality of control signals.

14.	The pulsed image capturing system of claim 9, wherein the plurality of multiplexers comprises:
a first multiplexer configured to select one of an internal light pulse synchronization signal and an external light pulse synchronization signal in response to a first selection signal;
a second multiplexer configured to select one of an internal global reset signal and an external global reset signal in response to a second selection signal; and
a third multiplexer configured to select one of an internal global hold signal and an external global hold signal in response to a third selection signal,
wherein the internal light pulse synchronization signal and the external light pulse synchronization control when the pulsed light pattern is generated,
the internal global reset signal and the external global reset signal control whether each of the plurality of pixels sets a reference illumination level in a current state, and
the internal global hold signal and the external global hold signal control whether the plurality of pixels hold an illumination change event indicating a change with respect to the reference illumination level for each of the plurality of pixels.

15.	The pulsed image capturing system of claim 14, wherein the first selection signal, the second selection signal, and the third selection signal are distinct signals.

16.	A method of operating a pulsed image capturing system including a dynamic vision sensor (DVS) including a pixel array having a plurality of pixels, the method comprising:
activating a global reset signal and transmitting the global reset signal to each of the plurality of pixels to set a reference illumination level for each of the plurality of pixels;
deactivating the global reset signal to enable each of the plurality of pixels to sense an illumination change amount with respect to the reference illumination level thereof;
activating a pulsed light pattern directed at an external object;
activating a global hold signal and transmitting the global hold signal to each of the plurality of pixels to hold an illumination change event indicating the illumination change amount thereof;
performing a DVS scanning and readout operation on event signals received from the plurality of pixels and generating a DVS output; and
deactivating the pulsed light pattern.

17.	The method of claim 16, wherein the pulsed light pattern includes a sequence of patterns.

18.	The method of claim 17, wherein each of sequence of patterns is the same,
wherein for each of the sequence of patterns, a configuration of the pulsed image capturing system is changed.

19.	The method of claim 18, wherein the configuration of the pulsed image capturing system includes an adjustable duration between activation of the pulsed light pattern and transmission of the global hold signal.

20.	The method of claim 18, wherein the configuration of the pulsed image capturing system includes adjustable sensitivity thresholds for each of the plurality of pixels.


21.	The method of claim 18, wherein the DVS output is generated for each of the sequence of patterns, and a weighted sum of the DVS output for each of the sequence of patterns is determined as a final DVS output.

22.	The method of claim 16, wherein the DVS output is generated at least two times and averaged to generate a final DVS output.


23.	The method of claim 16, wherein the DVS output is generated at least two times and combined to create a grey scale image of the pulsed light pattern.

24.	The method of claim 16, further comprising:
adjusting an intensity of the pulsed light pattern based on an amount of ambient light.

25.	The method of claim 16, further comprising:
increasing a duration between activation of the pulsed light pattern and transmission of the global hold signal to increase a sensitivity to contrast change.

26.	The method of claim 16, wherein the pulsed light pattern is deactivated before performing the DVS scanning and readout operation.


27.	A method of operating a pulsed image capturing system including a dynamic vision sensor (DVS) including a pixel array having a plurality of pixels, the method comprising:
synchronizing activation of a global reset signal and activation of a global hold signal to be transmitted to the plurality of pixels;
activating a pulsed light pattern directed at an external object between the activation of the global reset signal and the activation of the global hold signal;
generating event signals, by the plurality of pixels, according to a comparison between a predetermined threshold and a sensed illumination change amount resulting from the pulsed light pattern;
generating a DVS output using the event signals;
cleaning DVS-related artifacts from the DVS output; and
extracting a captured reflection of the pulsed light pattern from the DVS output after cleaning the DVS-related artifacts without additional image processing.

28.	A method of operating a pulsed image capturing system including a dynamic vision sensor (DVS) including a pixel array having a plurality of pixels, the method comprising:
synchronizing activation of a global reset signal to be transmitted to the plurality of pixels to set a reference illumination level for each of the plurality of pixels;
deactivating the global reset signal to enable each of the plurality of pixels to sense an illumination change amount with respect to the reference illumination level thereof;
activating a pulsed light pattern directed at an external object after deactivation of the global reset signal;
generating event signals, by the plurality of pixels, according to a comparison between a predetermined threshold and the sensed illumination change amount resulting from the pulsed light pattern; and
performing a DVS scanning and readout operation on the event signals received from the plurality of pixels and generating a DVS output.

"""


test1 = """1.   A memory module comprising:
an external resistor formed in a module board; and
a plurality of memory devices including a first memory device and a second memory device, and commonly connected to the external resistor,
wherein each of the plurality of memory devices comprises:
a first reception pad associated with receiving an impedance calibration command; and
a first transmission pad associated with transmitting the impedance calibration command, 
wherein each of the plurality of memory devices is configured to transfer the impedance calibration command to the first memory device, which is selected as a master, among the plurality of memory devices through a ring topology constituted by the first reception pad and the first transmission pad, and
wherein the first memory device is configured to perform an impedance calibration operation for the first memory device, to determine a resistance and a target output high level (VOH) voltage of an output driver, in response to the impedance calibration command, and is configured to transfer the impedance calibration command to the second memory device adjacent to the first memory device through the first transmission pad of the first memory device after performing the impedance calibration operation for the first memory device.
 
2.   The memory module of claim 1, wherein the plurality of memory devices further includes a third memory device, 
wherein the second memory device is configured to perform the impedance calibration operation for the second memory device in response to the impedance calibration command and is configured to transfer the impedance calibration command to the third memory device adjacent to the second memory device through the first transmission pad of the second memory device after performing the impedance calibration operation for the second memory device, and 
wherein the third memory device is connected to the first transmission pad of the second memory device. 

3.   The memory module of claim 1, wherein each of the plurality of memory devices further comprises:
an impedance pad connected to the external resistor;
a selection pad; and
an impedance calibration circuit connected to the first reception pad, the first transmission pad, the impedance pad, and the selection pad,
wherein the impedance calibration circuit comprises:
a detector connected to the selection pad, and configured to generate a detection signal;
a command controller connected to the first reception pad and the first transmission pad, wherein the command controller is configured to receive the impedance calibration command from one of the first reception pad and a corresponding command decoder; and
a calibration circuit connected to the external resistor through the impedance pad, wherein the calibration circuit is configured to perform the impedance calibration operation in response to a calibration enable signal from the command controller to output a pull-up control code and a pull-down control code to the output driver, and is configured to provide the command controller with a first comparison signal and a second comparison signal which indicate a completion of the impedance calibration operation.

4.   The memory module of claim 3, wherein the first memory device is selected as the master when a ground voltage or a power supply voltage is connected to the selection pad of the first memory device.

5.   The memory module of claim 3, wherein: 
the detector is configured to provide the command controller with the detection signal having a first logic level when a corresponding memory device is selected as the master; and
the detector is configured to provide the command controller with the detection signal having a second logic level when the corresponding memory device is not selected as the master.

6.   The memory module of claim 3, wherein:
the command controller is configured to enable the calibration enable signal and provide the calibration enable signal to the calibration circuit when the detection signal indicates that a corresponding memory device is selected as the master and the impedance calibration command is received from the first reception pad or the corresponding command decoder; 
the calibration circuit is configured to perform the impedance calibration operation in response to the impedance calibration command, and is configured to transit logic levels of the first comparison signal and the second comparison signal when the impedance calibration operation is completed; and
the command controller is configured to change tag information of the impedance calibration command to a first level based on transitions of the first comparison signal and the second comparison signal and is configured to transfer the impedance calibration command to an adjacent memory device through the first transmission pad. 

7.   The memory module of claim 3, wherein:
the command controller is configured to enable the calibration enable signal and provide the calibration enable signal to the calibration circuit when the detection signal indicates that a corresponding memory device is not selected as the master, tag information of the impedance calibration command has a first logic level, and the impedance calibration command is received from the first reception pad; 
the calibration circuit is configured to perform the impedance calibration operation in response to the impedance calibration command, and is configured to transit logic levels of the first comparison signal and the second comparison signal when the impedance calibration operation is completed; and
the command controller is configured to transfer the impedance calibration command to an adjacent memory device through the first transmission pad based on transitions of the first comparison signal and the second comparison signal.

8.   The memory module of claim 3, wherein:
the command controller is configured to disable the calibration enable signal and provide the calibration enable signal to the calibration circuit when the detection signal indicates that a corresponding memory device is not selected as the master, tag information of the impedance calibration command has a second logic level, and the impedance calibration command is received from the first reception pad or the corresponding command decoder; and
the command controller is configured to transfer the impedance calibration command to an adjacent memory device through the first transmission pad. 

9.   The memory module of claim 3, wherein the command controller comprises:
a path decision logic configured to receive the impedance calibration command from one of the first reception pad and the corresponding command decoder and is configured to provide a path information signal that indicates a reception path of the impedance calibration command and tag information;
a signal generator configured to determine a logic level of the calibration enable signal in response to the detection signal and the path information signal to output the calibration enable signal; and
a state machine configured to determine a logic level of an internal calibration mask signal based on the calibration enable signal and transitions of the first comparison signal and the second comparison signal, 
wherein the signal generator is further configured to provide the path decision logic with a path control signal to control a transfer of the impedance calibration command and a change of the tag information based on a state of the state machine.

10.  The memory module of claim 3, wherein the calibration circuit comprises:
a first code generator configured to generate the pull-up control code obtained from a result of comparing the target VOH voltage with a first voltage at a first node between a pull-up driver and a first replica pull-down driver;
a first code storing circuit configured to store the pull-up control code when the target VOH voltage becomes substantially the same as the first voltage;
a second code generator configured to generate the pull-down control code obtained from a result of comparing the target VOH voltage with a second voltage at a second node connected to the impedance pad; and
a second code storing circuit configured to store the pull-down control code when the target VOH voltage becomes substantially the same as the second voltage. 

11.   The memory module of claim 3, wherein each of the plurality of memory devices further comprises:
a data output circuit configured to output a data signal by driving data based on the pull-up control code and the pull-down control code, and 
wherein the data output circuit includes the output driver.

12.   The memory module of claim 11, wherein each of the plurality of memory devices further comprises:
a memory cell array configured to store the data and to provide the stored data to the data output circuit, and 
wherein the memory cell array includes a plurality of dynamic memory cells.

13.   A memory system comprising:
a memory module including an external resistor and a plurality of memory devices including a first memory device and a second memory device, wherein the external resistor is formed in a module board and the plurality of memory devices are commonly connected to the external resistor; and 
a memory controller configured to control the memory module, 
wherein each of the plurality of memory devices comprises:
a first reception pad associated with receiving an impedance calibration command; and
a first transmission pad associated with transmitting the impedance calibration command, and
wherein each of the plurality of memory devices is configured to transfer the impedance calibration command to the first memory device, which is selected as a master among the plurality of memory devices, through a ring topology constituted by the first reception pad and the first transmission pad, and
wherein the first memory device is configured to perform an impedance calibration operation for the first memory device, to determine a resistance and a target output high level (VOH) voltage of an output driver, in response to the impedance calibration command, and is configured to transfer the impedance calibration command to the second memory device adjacent to the first memory device through the first transmission pad of the first memory device after performing the impedance calibration operation for the first memory device.

14.   The memory system of claim 13, wherein each of the plurality of memory devices further comprises:
an impedance pad connected to the external resistor;
a selection pad; and
an impedance calibration circuit connected to the first reception pad, the first transmission pad, the impedance pad, and the selection pad,
wherein the impedance calibration circuit comprises:
a detector connected to the selection pad, and configured to generate a detection signal;
a command controller connected to the first reception pad and the first transmission pad, wherein the command controller is configured to receive the impedance calibration command from one of the first reception pad and a corresponding command decoder; and
a calibration circuit connected to the external resistor through the impedance pad, wherein the calibration circuit is configured to perform the impedance calibration operation in response to a calibration enable signal from the command controller to output a pull-up control code and a pull-down control code to the output driver, and is configured to provide the command controller with a first comparison signal and a second comparison signal which indicate a completion of the impedance calibration operation.

15.   The memory system of claim 13, wherein each of the plurality of memory devices is a low power double data rate 4 (LPDDR4) synchronous memory device.

16.   A method of calibrating multi-die impedance of a memory module including an external resistor and a plurality of memory devices, wherein the external resistor is formed in a module board and the plurality of memory devices are commonly connected to the external resistor, the method comprising:
selecting a first memory device of the plurality of memory devices as a master;
receiving, in a second memory device of the plurality of memory devices, an impedance calibration command; and
performing an impedance calibration operation sequentially in each of the plurality of memory devices from the first memory device using a ring topology constituted by a first reception pad and a first transmission pad included in each of the plurality of memory devices,
wherein the first reception pad is associated with receiving the impedance calibration command and the first transmission pad is associated with transmitting the impedance calibration command.

	17.   The method of claim 16, wherein performing the impedance calibration operation sequentially in each of the plurality of memory devices from the first memory device comprises:
	determining whether the first memory device matches with the second memory device.
	
	18.   The method of claim 17, wherein performing the impedance calibration operation sequentially in each of the plurality of memory devices from the first memory device further comprises:
	performing, in the first memory device, the impedance calibration operation for the first memory device, in response to the impedance calibration command, when the first memory device matches with the second memory device; and
	performing, in each of other memory devices which are not selected as the master, the impedance calibration operation sequentially by receiving the impedance calibration command from the first memory device or an adjacent memory device. 

	19.   The method of claim 17, wherein performing the impedance calibration operation sequentially in each of the plurality of memory devices from the first memory device further comprises:
	transferring, by the second memory device, the impedance calibration command to the first memory device using the ring topology, when the first memory device does not match with the second memory device; 
	performing, in the first memory device, the impedance calibration operation for the first memory device, in response to the impedance calibration command
	performing, in each of other memory devices which are not selected as the master, the impedance calibration operation sequentially by receiving the impedance calibration command from the first memory device or an adjacent memory device.

	20.   The method of claim 16, wherein each of the plurality of memory devices is configured to determine a resistance and a target output high level voltage of an output driver by performing the impedance calibration operation, and
	wherein the output driver is configured to output data externally to each of the plurality of memory devices.  
"""

#print(test)

#matchObj = re.match(r'[0-9]\.',test)

#print(matchObj.group())

#list = re.findall(r'[0-9]{1,2}\..*\n\n',test,re.M|re.S)


claims = {}
filename = '8836S-1189 claims.txt'
claimsString = file_reader.getStringFromTxt(filename)

list = re.findall(r'[0-9]{1,2}\..*$',claimsString,re.M)

print(list)
print(len(list))

for i in list:
    claimNo = re.match(r'[0-9]{1,2}',i).group(0)
    print(claimNo)
    #print(type(claimNo))
    #matchObj = re.search(r'claim [0-9]{1,2}',i,re.I)
    
    claims[claimNo] = []

    
    depClaimRegex = r'(claim) (\d+)'
    
    matchObj = re.search(depClaimRegex,i,re.I)
    if matchObj:
        parClaimStr = matchObj.group(0)
        
        #depClaimNo = re.sub(depClaimRegex, r'\1', i)
        parClaimNo = parClaimStr.lower().replace('claim ','')
        print('parent: ' + parClaimNo)
                
        if parClaimNo in claims:
            claims[parClaimNo].append(claimNo)
        #depClaimNo = depClaimStr.replace()
        #print(matchObj.group(0))
        
    else:
        print('no match')
    
    
    #claims.update()
    

print(claims)

graph = pydot.Dot(graph_type='graph')

for i in claims:
    print(i)
    # we can get right into action by "drawing" edges between the nodes in our graph
    # we do not need to CREATE nodes, but if you want to give them some custom style
    # then I would recomend you to do so... let's cover that later
    # the pydot.Edge() constructor receives two parameters, a source node and a destination
    # node, they are just strings like you can see
    for j in claims[i]:
        edge = pydot.Edge(i, j)
        graph.add_edge(edge)
    
    # and we obviosuly need to add the edge to our graph

currentTime = str(datetime.datetime.now()).split('.')[0].replace('-','').replace(' ','').replace(':','')

fileName = '{}_claims_{}.png'.format(filename.replace('.txt',''),currentTime)    
graph.write_png(fileName)
print("flowchart generated...")

#print(filereadtest.getStringFromTxt())

#test2 ="ABC"
#print(re.match(r'A',test2).group())

#test.split

#print("test")